# Prepare environment.yml file
name: cytotrace2-py
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - python=3.9.19
  - anndata
  - matplotlib
  - numpy
  - pandas
  - pytorch=2.0.0
  - scanpy
  - scikit-learn=1.0.2
  - scipy
  - seaborn
  - notebook # optional, for jupyter notebook




